name: "Build contracts"
on:
  - push

jobs:
  build-cbor:
    name: "Build API"
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make install_solc_linux
      - name: Compile contract file
        run: make
